### ISSUE TITLE
Updating ratelimit and period during runtime

### ISSUE THREAD

**Issue by Bubblbu** [uburuntu/throttler#2]
Would the implementation support an updating of the `ratelimit` during runtime depending on the responses from the API?

**Comment by uburuntu** [comment]
Hello!

Yes, you can change parameters during execution, and already running corutines will wait with previous values. But now it's only through access to private attributes.

I can add special method like `def update_limits(self, rate_limit, period)`. Is that what you need?

Also you can recreate `Throttler` instance, it's lightweight enough.

**Comment by Bubblbu** [comment]
So, any coroutines that are already running (i.e, after `create_task` or `ensure_future`) will be running with the values at time of creation? Updating those values will only impact newer coroutines.

Still pretty new to asyncio and trying to wrap my head around the new concepts :D

The update method seems to be the cleaner implementation no? But I can also see that simply creating a new instance works totally fine too.

**Comment by uburuntu** [comment]
> So, any coroutines that are already running (i.e, after create_task or ensure_future) will be running with the values at time of creation?

Yep, but only for last cycle inside of `Throttler`. I.e. little time.

But I think will be better if you recreate `Throttler` instance with new parameters. As I said, it's lightweight enough 😉
